---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/rwd
  label: Responsive Web Design
  create: all
  match: "**/*"
- type: directory
  path: src/layers
  label: Cascade Layers
  create: all
  match: "**/*"
- type: directory
  path: src/toggles
  label: CSS Toggles
  create: all
  match: "**/*"
- type: directory
  path: src/scope
  label: Scope
  create: all
  match: "**/*"
- type: directory
  path: src/elsewhere
  label: Elsewhere
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
